### ISSUE TITLE
Add another compressor support

### ISSUE THREAD

**Issue by abhi1693** [toughdeveloper/oc-imageresizer-plugin#13]
`TniyPNG` is a great addon but it is a paid option which makes it difficult to use if you have many images on the website. I think you should implement a free library which will compress the the images and is as good as `TinyPNG`.

For this, I think [resmush.it/](http://resmush.it/) is a good candidate. Please look into it. I tried to integrate it with your library but I ran into some issues since I'm new to `OctoberCMS` and `Laravel`.

Try this [link](http://api.resmush.it/ws.php?img=https://tux-tips.com/storage/app/media/download.png)

**Comment by toughdeveloper** [comment]
Hey @abhi1693 

Appreciate the feedback. Will have a play around with the link you supplied, a forever free solution would be ideal. Will get back to you when I've had chance to progress further with this.

**Comment by matteotrubini** [comment]
@abhi1693 can you open a PR? I would be happy to review and merge it.

**Comment by matteotrubini** [comment]
This plugin is being migrated to core (see #55), so we are trying to figure out what issues are still relevant to invite to reopen them in core.

Issues that will remain inactive in next 30 days will be closed.

**Comment by LukeTowers** [comment]
@abhi1693 see https://github.com/LukeTowers/oc-tinypng-plugin/blob/master/Plugin.php for how you can implement this with the new core functionality. @matteotrubini you can close this issue.
