### ISSUE TITLE
Images not working when they have a space in the filename

### ISSUE THREAD

**Issue by toughdeveloper** [toughdeveloper/oc-imageresizer-plugin#15]
Quoted from ioCare October CMS review:

> Note: Make sure image do not have space in it. I struggled for many days to make it working and finally realized that my image file names were like - "Media Lab.jpg".

**Comment by toughdeveloper** [comment]
Through a variety of testing, I've been unable to replicate the issue. If anyone is also having this same issue, I would greatly appreciate any more information you may be able to provide.

**Comment by bkrajendra** [comment]
I'm having this issue on windows+apache (xampp). Maybe its related to OS.

**Comment by bkrajendra** [comment]
I'll have to check it again. I guess it may be as i used to copy past path from october cms media manager, which introduces "%20" for space in url or file name. so if u want to replicate try introducing %20 for space in url path.

**Comment by mauserrifle** [comment]
I fixed this issue in the following pull request: 
https://github.com/toughdeveloper/oc-imageresizer-plugin/pull/48

**Comment by yapsr** [comment]
@toughdeveloper I updated tot OctoberCMS v1.0.488 and this bug appeared. Could you into the PR above, please?

**Comment by damianlewis** [comment]
I have the same issue. I think it's related to using Media Manager. Images uploaded by the Media Manager retain the file name format. So if an image is uploaded with a space in its filename, that space is retained, leading to broken images.

It would be better if the Media Manager converted filenames to a URL friendly format.

**Comment by fresswolf** [comment]
I had the same problem and use url_decode as a workaround:
`{{ image|media|url_decode|resize(400) }}`

**Comment by matteotrubini** [comment]
@fresswolf @damianlewis @yapsr can you confirm if #48 solve your problems?

**Comment by fresswolf** [comment]
@matteotrubini works for me

**Comment by damianlewis** [comment]
@matteotrubini the #48 fix worked for me.

**Comment by matteotrubini** [comment]
#48 merged
