### ISSUE TITLE
Watermarking?

### ISSUE THREAD

**Issue by sigfriedseldeslachts** [toughdeveloper/oc-imageresizer-plugin#17]
Hi,

I'm making a site, and I would love to see a watermarking feature.
Is this some how possible?

Regards
Me

**Comment by toughdeveloper** [comment]
Hey,

Sure it would be possible, I would likely implement with a similar approach to the tiny PNG compression (have default options within settings, then in the `diskName` method append 'watermark' to create a unique file path if enabled, finally in the resize method before we compress check and apply the watermark).

I'm happy to look at this at some point but unfortunately can't give you a timescale. If you/anyone would like to approach, feel free to submit a PR.

**Comment by sigfriedseldeslachts** [comment]
Hi,

I looked at your source code, but I have no idea how the compression works.
I saw this:
```php
// Resize it
$thumb = $this->file->getThumb($width, $height, $this->options);
```
But where is the method getThumb()?

Regards
Sigfried

**Comment by toughdeveloper** [comment]
The plugin quite heavily relies on Octobers built in image resizer, most of which is done in the class `October\Rain\Database\Attach\File class`

Check out https://github.com/octobercms/library/blob/master/src/Database/Attach/File.php#L375

This class is instantiated to `$this->file` in the construct - https://github.com/toughdeveloper/oc-imageresizer-plugin/blob/master/classes/Image.php#L41

**Comment by sigfriedseldeslachts** [comment]
I see now.

I'm going to try this and make it similar to the the Tiny PNG method. If everything goes well I should be finished tonight or tomorrow.

Regards
Sigfried

**Comment by matteotrubini** [comment]
@sigfriedseldeslachts are you still interested in submit a PR about this feature?

**Comment by sigfriedseldeslachts** [comment]
Yeah, but I need to find some time for that. I have it rather busy nowadays.

**Comment by zlobec** [comment]
+1

**Comment by Pixinside** [comment]
+1

**Comment by matteotrubini** [comment]
This plugin is being migrated to core (see #55), so we are trying to figure out what issues are still relevant to invite to reopen them in core.

Issues that will remain inactive in next 30 days will be closed.

**Comment by LukeTowers** [comment]
See https://github.com/LukeTowers/oc-tinypng-plugin/blob/master/Plugin.php for an example of how you could create a plugin for the new resize functionality being added to core. @matteotrubini you can close this
