### ISSUE TITLE
Prevent/remove duplicate image

### ISSUE THREAD

**Issue by toughdeveloper** [toughdeveloper/oc-imageresizer-plugin#18]
Look into minimise duplicated images (following feedback from Lilydale Heights College): 

> Very useful and practical utility. It gives some new opportunities in using Media Library and optimise media content. I use it a lot especially with TinyPNG. However, it has a peculiarity as well.
>
> When using RainLab Blog you can apply getThumb to a featured image and you have your thumbs created in the same upload folder where your original file is stored.
>
> The Image Resizer in this situation creates a new upload folder, copy the original in to it as a file without extension, then creates thumbs there.
>
> As a result, you have 2 copies of the original file in different folders, double your file structure and used storage space. If your storage is limited, this feature becomes an issue. I am not sure if there is a good reason to keep the second copy of the original file.

**Comment by maartenmachiels** [comment]
Hi, loving your work, thanks for a great plugin. 

Is there any update on preventing the duplication of the images? 
In one of my sites there are thousands of images and this tends to make the storage folder huge.

Also, something that's I cannot seem to get around is that thumbnails are orphaned in the file system when you delete the original connected image. Do you have any idea how to circumvent this? The project of my client is growing and growing and I'm running out of disk space :-(

**Comment by matteotrubini** [comment]
Close in favour of #45
