### ISSUE TITLE
Add thumb type in model list of builder plugin

### ISSUE THREAD

**Issue by Zmove** [toughdeveloper/oc-imageresizer-plugin#20]
Hello,

I just saw that you can easily display images in backend using the thumb type and that's fantastic !

However, the builder plugin don't know this type and when you open the model list into the builder, it can't display any time in front of the image column.

Would be really great to alter that list to add the thumb type, so it would be directly selectable in the builder plugin

**Comment by toughdeveloper** [comment]
@Zmove - Sorry for the delay. I've had a look and it seems this is probably something to point towards the builder plugin: https://github.com/rainlab/builder-plugin/issues . 

The thumb column type is registered inline with the documentation (https://octobercms.com/docs/backend/lists#custom-column-types). It seems the builder plugin currently doesn't support custom column types.

Thanks,
Matt
