### ISSUE TITLE
Issue with EDGE build 423

### ISSUE THREAD

**Issue by markandmedia** [toughdeveloper/oc-imageresizer-plugin#25]
I'm testing some of my websites to see how they work on the laravel 5.5 version of octoberCMS (current build 423). You plugin does not seem te work in this version.
This is of course no problemen for now, I thought to mention is just in case you didn't notice it.

I love you're plugin!

**Comment by that0n3guy** [comment]
The problem is that resize is looking for a file with the name of `thumb__300x200_0_0_crop.jpg` but the file actually stored on the drive is `thumb__300_200_0_0_crop.jpg`.

Notice that there is an "x" vs "_" (300**x**200 )

**Comment by that0n3guy** [comment]
Easy fix is to change this line: https://github.com/toughdeveloper/oc-imageresizer-plugin/blob/91f9b925f8fe522fa8a09cd1f7a7c672f501c880/classes/Image.php#L272

so that the `'x'` is `'_'`.   Tested and it seems to work.

**Comment by toughdeveloper** [comment]
Hi, sorry for the delay. This seems to affect some users and not others, so unfortunately I don't think the fix is to replace the `x` with an `_`. May be down to the October version, but the plugin should be backward compatible where possible. I will review this and get a fix together ASAP. Thanks for your help and for using the plugin.

**Comment by that0n3guy** [comment]
I'm pretty sure its a october version 420 and up thing (because of laravel 5.5 and its updated dependencies maybe?).    I do agree that the hard coded x or _ probably isn't the best way to do it though so there is probably a better fix.

**Comment by TimFoerster** [comment]
I have the same problem.
in template: `thumb__473x299_0_0_auto.png` on disk: `thumb__473_299_0_0_auto.png`

**Comment by toughdeveloper** [comment]
Apologies for the delay in this.

Users with `edgeUpdates` set to true will now get an update to `1.3.5`.

Any problems, please let me know.
