### ISSUE TITLE
Rendered thumbnail file has different filename than is output from the twig plugin

### ISSUE THREAD

**Issue by lthurston** [toughdeveloper/oc-imageresizer-plugin#29]
In other words, I'm rendering a thumbnail like this:

`<img src="{{ year.hero_image | media | resize(538) }}" />`

Which outputs this:

`<img src="http://my.dev/storage/app/uploads/public/807/0db/830/thumb__538_0_0_0_auto.png">`

But the file on disk is:

`thumb__538x0_0_0_auto.png`

I've managed to make it work by changing the the getThumbFilename() function to alter the filename template -- haven't had a change to dig in any further than that -- and it works.

Seems like an odd bug, unless there has been a change in thumbnail filename creation internally, and this plugin is mirroring / duplicating that code. I'll dig a little deeper tomorrow and see if I can find a better solution.

**Comment by toughdeveloper** [comment]
Hi,  

Please can you confirm the version of October cms that you’re using? The file naming changed after version 420 so you may need to upgrade the core framework.
Thanks

**Comment by lthurston** [comment]
Ah, yeah, that's it. Thanks!
