### ISSUE TITLE
The partial '_field_thumb.htm' is not found.

### ISSUE THREAD

**Issue by trollkotze** [toughdeveloper/oc-imageresizer-plugin#38]
The README, under the heading [Usage in Backend List](https://github.com/toughdeveloper/oc-imageresizer-plugin#usage-in-backend-list), says:

> The image resizer can also be used on backend lists with the type of `thumb`, e.g.
> ```
> image:
> 	label: Image
> 	type: thumb
> ```

However, when I use it like this, i.e. adding such a field in a theme.yaml, I get this error when trying to edit the theme settings:
> The partial '_field_thumb.htm' is not found.

Is the README wrong or have I misunderstood something?

I have the current version, 1.3.5 installed.

**Comment by lzomedia** [comment]
me to i get the same issue

**Comment by mediaclinic** [comment]
Same problem here.

**Comment by matteotrubini** [comment]
If anyone can open a PR I would be happy to review and merge it.

**Comment by mmorells** [comment]
Seems that the Builder plugin (https://octobercms.com/plugin/rainlab-builder) doesn't support the "thumb" custom field type, which Image Resizer requires. Is it possible to support Builder types like Mediafinder? https://github.com/toughdeveloper/oc-imageresizer-plugin/issues/20#issuecomment-295628958

**Comment by matt-pawley** [comment]
Unfortunately it seems October only supports custom column types for plugin lists and does not support them for `theme.yaml` form fields.

The thumb column type is registered inline with the documentation (https://octobercms.com/docs/backend/lists#custom-column-types). It seems the October CMS currently doesn't support custom column types for theme form fields/

I would raise this as a feature request in October CMS repository - https://github.com/octobercms/october/issues

Will close this issue, but I've misunderstood please let me know and I will re-open.
