### ISSUE TITLE
Error on resize method if octobercms on dev dependencies.

### ISSUE THREAD

**Issue by CptMeatball** [toughdeveloper/oc-imageresizer-plugin#44]
On the newest dev builds of OctoberCMS, the `|resize` twig method fails. This causes the method to always return the "no image" fallback image. Rolling back to Build 443 on stable fixes this issue.

**Comment by matteotrubini** [comment]
Is this issue still present on current builds? Can you provide a step-by-step guide to replicate it?

**Comment by CptMeatball** [comment]
Not sure. Will re-open if I run into the problem again.
