### ISSUE TITLE
Temporary file is not deleted

### ISSUE THREAD

**Issue by multiwebinc** [toughdeveloper/oc-imageresizer-plugin#45]
I have the following file in my `media` folder:

```
-rw-rw-r-- 1 user user 4120619 Dec  4 09:05 images/IMG_0281.JPG
```

So I put the following in one of my views to use this image:

```
    <img src="{{ 'images/IMG_0281.JPG'|media|resize(600,600) }}">
```

This creates (in my case) the following directory tree in the `uploads/public` directory:

```
73f
└── [       4096]  fe6
    └── [       4096]  021
        ├── [    4120619]  73ffe6021b91d705a567bed46a2d7871
        └── [     107565]  thumb__600_600_0_0_auto.JPG
```

However as you notice here, the file `73ffe6021b91d705a567bed46a2d7871` is actually just the image (verified with md5sum). This needlessly doubles the storage space for the original full-size image. Instead **only** the thumbnail should be stored and the original image should be only in the original directory.

**Comment by multiwebinc** [comment]
@toughdeveloper You still alive?

**Comment by matteotrubini** [comment]
@toughdeveloper there was a reason to retain that files?

**Comment by maartenmachiels** [comment]
Hi guys, what's the status on this? Would be great if we could get this fixed as the duplicates eat up a lot of storage space.
