### ISSUE TITLE
Image not found after update to build 446

### ISSUE THREAD

**Issue by roojai** [toughdeveloper/oc-imageresizer-plugin#49]
Did a system update and my resized images disappeared. Anyone else having this problem?

**Comment by maartenmachiels** [comment]
I noticed the same thing. For me it had something to do with spaces in filenames. Removing spaces from original filenames did the trick for me. Anyone else with this issue?

**Comment by roojai** [comment]
I just updated a different site, and same problem. This is build 447 now. I just see the default "no image found" image displayed for all images. And when I check the folders, (eg /storage/app/uploads/public/a61/363/a76) I find that the generated thumbs are also using the default "no image found" image. 

There are no spaces in my file names so thats not it for me

**Comment by roojai** [comment]
My correction! It IS spaces in the filenames that is causing the problem. If there is a space in the folder or image file then the image path fails.

And by disabling the "no image found" function I can see that the system IS inserting %20 for spaces, but it is also inserting the route directory for the server. 

For example:
/home/mywebsites/thiswebsite.com//storage/app/uploads/public/492/8a7/97b/thumb__746_746_0_0_crop.jpg

When it should be thiswebsite.com/storage/app/uploads/public/492/8a7/97b/thumb__746_746_0_0_crop.jpg

**Comment by roojai** [comment]
https://github.com/toughdeveloper/oc-imageresizer-plugin/pull/48
