### ISSUE TITLE
Choose how to crop

### ISSUE THREAD

**Issue by ghost** [toughdeveloper/oc-imageresizer-plugin#51]
Hello,

When you use the crop method for an image, the plugin always consider the focus to the center of the image.

Is it possible to add some parameters to allow to choose how to crop the image ?

If it's already possible, how could I do that ? I tried to play with the offset parameter, but it doesn't seems to do that.

Thank you

Alex

**Comment by setianke** [comment]
Interested in this as well

**Comment by matteotrubini** [comment]
https://octobercms.com/docs/api/october/rain/database/attach/resizer
