### ISSUE TITLE
Generate unique file cache key based on relative (not absolute) path

### ISSUE THREAD

**Issue by lthurston** [toughdeveloper/oc-imageresizer-plugin#52]
The issue is that with some deployment setups, the path to the latest release (with symlinks resolved) changes with each build. When this happens, the paths to all files on the site change too, meaning they get regenerated with each release.

The solution would be to determine if a file has been cached based on an MD5 of the original filename provided to the Image::__contruct() method, rather that the full disk name.

I've got a PR for this which I will submit shortly.

**Comment by matteotrubini** [comment]
Closed by #53
