### ISSUE TITLE
Media-Library & Spaces

### ISSUE THREAD

**Issue by gbaumeister** [toughdeveloper/oc-imageresizer-plugin#61]
Using the plugin with twig-filter `| media`  causes an "Image not found" if the image-name contains a space-character.

The `media` filter HTML-encodes all URL-unsafe characters, causing space characters to be converted to `%20`. Therefore it is not possible to use the plugin in conjunction with the media-library. 

Example-Code:
` 'path/to/image with a space.jpg' | media | resize()`

**Comment by matteotrubini** [comment]
#48 solve your issue?

**Comment by gbaumeister** [comment]
Yes - thank you
