### ISSUE TITLE
Image not found when URL contains %20

### ISSUE THREAD

**Issue by setianke** [toughdeveloper/oc-imageresizer-plugin#63]
Images using following markup are not found

`{{ record.preview_image_media | media |  resize(125, 250, { mode: 'crop'}) }}`

When orignal image path contains URL with %20 in it 
`/storage/app/media/image%20Default.jpg`

**Comment by matteotrubini** [comment]
#48 solve your issue?

**Comment by setianke** [comment]
Yes it does - thank you for the quick response and sorry, was not aware there was already a PR for the issue.
