### ISSUE TITLE
"touch(): Utime failed: Operation not permitted" error after latest update

### ISSUE THREAD

**Issue by haralake** [toughdeveloper/oc-imageresizer-plugin#66]
Hello! After latest update from 1.3.6 to 1.4 i get this error:
`An exception has been thrown during the rendering of a template ("touch(): Utime failed: Operation not permitted").`

After i downgrade to old version 1.3.6 everything is working ok.

**Comment by matteotrubini** [comment]
Sounds like a file permissions issue. Make sure the owner and permissions are correct and/or clean all caches, otherwise please report detailed info about your system to investigate, thankyou!

**Comment by haralake** [comment]
Is a Ubuntu 18 server with Apache and php 7.2. It is local environment (Windows 10 Ubuntu Subsystem). I clean all cache files in Octobercms but error persist. When i go to older version is working without any problems. I work with your excellent plugin a long time now and this is the first time that happens.

**Comment by haralake** [comment]
On error log i get this:
`ErrorException: touch(): Utime failed: Operation not permitted in /mnt/c/Projects/www/theme/plugins/toughdeveloper/imageresizer/classes/Image.php:97`

**Comment by matteotrubini** [comment]
It may be related WLS, but I never used it.
Can you try to `touch` a file in shell to check if you get the same error, please?

**Comment by VGirol** [comment]
I have the same issue.
In shell, this command succeed : 
php -r 'touch("path/to/file", 1581557759);'

**Comment by matteotrubini** [comment]
@VGirol are you using WLS too?

**Comment by VGirol** [comment]
@matteotrubini No, i am on Ubuntu 18 with Apache2 and PHP 7.3.

**Comment by matteotrubini** [comment]
@VGirol are you using the same user to touch the file on shell? Can you share file permission details?

**Comment by VGirol** [comment]
@matteotrubini I realized i wasn't using the same user.
This new command failed : 
$ sudo -u www-data php -r 'touch("path/to/file", 1581557759);'

PHP Warning:  touch(): Utime failed: Operation not permitted in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. touch() Command line code:1

File permissions : 
-rwxrwxrwx 1 bigcheaf users 14437 févr. 13 02:35 /path/to/file

It's strange : www-data seems to have read/write permissions on the file...

**Comment by matteotrubini** [comment]
I think about missing permission on parent folder.

Now it seems clear to me that also other errors was caused by wrong permissions, I close.
