### ISSUE TITLE
Unlink throwas an exception after the update

### ISSUE THREAD

**Issue by vosco88** [toughdeveloper/oc-imageresizer-plugin#67]
After the latest update of the plugin I started to get the exception when using the resize filter. 

`ErrorException: unlink(file): No such file or directory in /plugins/toughdeveloper/imageresizer/classes/Image.php:123`

https://github.com/toughdeveloper/oc-imageresizer-plugin/blob/b0bfde3da080c48647c99e7f83bb017f1a21b6f1/classes/Image.php#L123

**Comment by matteotrubini** [comment]
Did you try to completely clean the cache?

Anyway, we can implement this logic to better handle errors, using `Log::warning($error)` to trace errors: https://www.php.net/manual/en/function.unlink.php#123175

Can you make a PR to cover this?

**Comment by vosco88** [comment]
I did try cache cleaning, I plan to do a bit more testing. 
But because of the time I do not know when I'll be able to do it as well as with PR.

**Comment by arc92** [comment]
Hi @matteotrubini base on your bug report i fix that line, if any problem see let me be aware to fix it

**Comment by Trysystems** [comment]
The problem is still here if we resize file from media library, because there is no tmp file.

**Comment by matt-pawley** [comment]
Fixed in #69 and published as `1.4.1`. Thanks.
