### ISSUE TITLE
Should ignore svg

### ISSUE THREAD

**Issue by GORobert** [toughdeveloper/oc-imageresizer-plugin#70]
Sometimes i upload .svg images into media library, for example for logo. Using:
{{ record.logo|media|resize(false,43) }}
i get the link to non existing image - 'thumb__0_43_0_0_auto.svg'.
SVG's should be ingored when resizing, is there an option for this in settings - don't see anything in documentation

**Comment by maartenmachiels** [comment]
Hi @GORobert 

I've encountered the same problem before and solved it by testing for "svg" in twig:
```
{% if 'svg' in record.logo | media %}
  <img src="{{ record.logo | media }}" />
{% else %}
  <img src="{{ record.logo | media | resize(500) }}" />
{% endif %}
```
Could this be useful?

A lot of stuff could be uploaded to the media finder. Maybe we should do some kind of MIME testing...

**Comment by GORobert** [comment]
Hey thanks, meantime i came with similar workaround:

{% if record.logo|split('.')|last == 'svg' %}
<img src="{{ record.logo|media }}" />
{% else %}
<img src="{{ record.logo|media|resize(false,43) }}" />
{% endif %}

"in" may be faster than |split|last maybe, but you don't have to use |media.
But yeah it would be good to add some mime testing, or param to whitelist provided extensions and ignore the rest. Or maybe achieve whitelisting in configuration file
