### ISSUE TITLE
Error happens when use webp type image on server, but normal on local

### ISSUE THREAD

**Issue by kuleyu** [toughdeveloper/oc-imageresizer-plugin#71]
Server environment: CentOS 7.2   LNMP
Local environment: Windows10    WNMP

example:
when use `{{ 'assets/images/theme/bg-presence.webp'|theme }}`, both server and local worked well.
when use `{{ 'assets/images/theme/bg-presence.webp'|theme|resize(200,200) }}`, server throws error, but local works well.

Error info: 
```
# /www/wwwroot/octobercms/vendor/october/rain/src/Database/Attach/Resizer.php line 527

        break;
    case 'image/png':
        $img = @imagecreatefrompng($filePath);
        $this->retainImageTransparency($img);
        break;
    case 'image/webp':
        $img = @imagecreatefromwebp($filePath);               ##here line 527##
        $this->retainImageTransparency($img);
        break;
    default:
        throw new Exception(sprintf('Invalid mime type: %s. Accepted types: image/jpeg, image/gif, image/png, image/webp.', $this->mime));
        break;
}
```
![image](https://user-images.githubusercontent.com/25771340/78866219-918c3700-7a71-11ea-8925-198190b692d1.png)

**Comment by matteotrubini** [comment]
WebP seems not to be supported by your GD installation.
https://www.php.net/manual/en/intro.image.php
> To find out which formats that was available to GD during compilation, use the `gd_info()` function
