### ISSUE TITLE
Tiny PNG / limit the number of requests at a time

### ISSUE THREAD

**Issue by superoleg** [toughdeveloper/oc-imageresizer-plugin#72]
if there are a large number of images, the site displays an error due to processing time. Therefore you need to click through all the pages of the site yourself.

**Comment by toughdeveloper** [comment]
Hi @superoleg 

I would recommend in this case pre-resizing the images to the desired size when they are uploaded or on a scheduled task - https://github.com/toughdeveloper/oc-imageresizer-plugin#usage-in-php

**Comment by matt-pawley** [comment]
Closing as best solved by pre-processing.
