### ISSUE TITLE
Resize not work

### ISSUE THREAD

**Issue by ribsousa** [toughdeveloper/oc-imageresizer-plugin#9]
{{ image.path | resize(500) }}

output:

could not load the  image http://gleebe.org/storage/app/uploads/public/8c1/95c/131/thumb__500x_0_0_auto.jpg

When I specify the second parameter it works
{{ image.path | resize(500, 250) }}

**Comment by toughdeveloper** [comment]
Thanks will take a look and get a fix ASAP. In the mean time you can pass 0 in as the second parameter for auto height. Thanks

**Comment by ribsousa** [comment]
It's works! whit  filter |media

`{{ 'crowd-bw-dark.jpg'|media | resize(1920, 0) }}`

It's not works! whit  filter |theme

`{{ 'assets/img/pages/contact/header/img-01.jpg' | theme | resize(1920,0) }}`

**Comment by toughdeveloper** [comment]
What is format of your url? Set in `config/app.php` or `APP_URL` if you are using `.env` files. A trailing slash seems to break the theme which I can take a look at in this fix too.

**Comment by ribsousa** [comment]
`config/app.php`
`'url' => 'http://gleebe.org/',`

No using `.env` files

**Comment by toughdeveloper** [comment]
@ribsousa - Sorry for delay. Simply remove the trailing slash so the URL becomes `http://gleebe.org` and it will work fine. Both issues mentioned will be fixed either way in next few days by - https://github.com/toughdeveloper/oc-imageresizer-plugin/pull/10

**Comment by toughdeveloper** [comment]
Fixed a of https://github.com/toughdeveloper/oc-imageresizer-plugin/commit/fa70eea3f12c398a271880f12bfc32935f47d793

Please update and let me know if you have any further issues
